package beans;
// Generated Jun 2, 2020, 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import util.HibernateUtil;

/**
 * Poljoprivrednik generated by hbm2java
 */
public class Poljoprivrednik  implements java.io.Serializable {


     private String korisnickoImePolj;
     private Korisnik korisnik;
     private String ime;
     private String prezime;
     private Date datumRodjenja;
     private String telefon;
     private String email;
     private String mestoRodjenja;
     private Set<Rasadnik> rasadniks = new HashSet<Rasadnik>(0);
     private Set<Detalji> detaljis = new HashSet<Detalji>(0);

    public Poljoprivrednik() {
    }

	
    public Poljoprivrednik(Korisnik korisnik, String ime, String prezime, Date datumRodjenja, String mestoRodjenja, String telefon, String email) {
        this.korisnik = korisnik;
        this.ime = ime;
        this.prezime = prezime;
        this.datumRodjenja = datumRodjenja;
        this.telefon = telefon;
        this.email = email;
        this.mestoRodjenja = mestoRodjenja;
    }
    public Poljoprivrednik(Korisnik korisnik, String ime, String prezime, Date datumRodjenja, String telefon, String email, String mestoRodjenja, Set<Rasadnik> rasadniks, Set<Detalji> detaljis) {
       this.korisnik = korisnik;
       this.ime = ime;
       this.prezime = prezime;
       this.datumRodjenja = datumRodjenja;
       this.telefon = telefon;
       this.email = email;
       this.mestoRodjenja = mestoRodjenja;
       this.rasadniks = rasadniks;
       this.detaljis = detaljis;
    }
   
    public String getKorisnickoImePolj() {
        return this.korisnickoImePolj;
    }
    
    public void setKorisnickoImePolj(String korisnickoImePolj) {
        this.korisnickoImePolj = korisnickoImePolj;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public Date getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(Date datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMestoRodjenja() {
        return this.mestoRodjenja;
    }
    
    public void setMestoRodjenja(String mestoRodjenja) {
        this.mestoRodjenja = mestoRodjenja;
    }
    public Set<Rasadnik> getRasadniks() {
        return this.rasadniks;
    }
    
    public void setRasadniks(Set<Rasadnik> rasadniks) {
        this.rasadniks = rasadniks;
    }
    public Set<Detalji> getDetaljis() {
        return this.detaljis;
    }
    
    public void setDetaljis(Set<Detalji> detaljis) {
        this.detaljis = detaljis;
    }


public static void sacuvajPoljoprivrednika(Poljoprivrednik p) {
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        session.save(p);
        session.getTransaction().commit();
        session.close();
    }

}


