package beans;
// Generated Jun 2, 2020, 10:56:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import util.HibernateUtil;

/**
 * Preduzece generated by hbm2java
 */
public class Preduzece  implements java.io.Serializable {


     private String korisnickoImePred;
     private Korisnik korisnik;
     private String naziv;
     private Date datum;
     private String mesto;
     private String email;
     private Set<Onlineprodavnica> onlineprodavnicas = new HashSet<Onlineprodavnica>(0);

    public Preduzece() {
    }

	
    public Preduzece(Korisnik korisnik, String naziv, Date datum, String mesto, String email) {
        this.korisnik = korisnik;
        this.naziv = naziv;
        this.datum = datum;
        this.mesto = mesto;
        this.email = email;
    }
    public Preduzece(Korisnik korisnik, String naziv, Date datum, String mesto, String email, Set<Onlineprodavnica> onlineprodavnicas) {
       this.korisnik = korisnik;
       this.naziv = naziv;
       this.datum = datum;
       this.mesto = mesto;
       this.email = email;
       this.onlineprodavnicas = onlineprodavnicas;
    }
   
    public String getKorisnickoImePred() {
        return this.korisnickoImePred;
    }
    
    public void setKorisnickoImePred(String korisnickoImePred) {
        this.korisnickoImePred = korisnickoImePred;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Onlineprodavnica> getOnlineprodavnicas() {
        return this.onlineprodavnicas;
    }
    
    public void setOnlineprodavnicas(Set<Onlineprodavnica> onlineprodavnicas) {
        this.onlineprodavnicas = onlineprodavnicas;
    }


public static void sacuvajPreduzece(Preduzece p) {
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        session.save(p);
        session.getTransaction().commit();
        session.close();
    }

}


