package beans;
// Generated Jun 2, 2020, 10:56:56 PM by Hibernate Tools 4.3.1

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import util.HibernateUtil;




/**
 * Sadnicezasadjene generated by hbm2java
 */
public class Sadnicezasadjene  implements java.io.Serializable {


     private Integer idSadnice;
     private Magacin magacin;
     private int napredovanje;
     private int kolona;
     private int red;
            

    public Sadnicezasadjene() {
    }

	
    public Sadnicezasadjene(Magacin magacin) {
        this.magacin = magacin;
    }
    public Sadnicezasadjene(Magacin magacin, int napredovanje) {
       this.magacin = magacin;
       this.napredovanje = napredovanje;
    }

    public Sadnicezasadjene(Sadnicezasadjene sadnica) {
        this.magacin = sadnica.getMagacin();
        this.napredovanje = sadnica.getNapredovanje();
        this.kolona = sadnica.getKolona();
        this.red = sadnica.getRed();
    }
   
    
    
    public Integer getIdSadnice() {
        return this.idSadnice;
    }
    
    public void setIdSadnice(Integer idSadnice) {
        this.idSadnice = idSadnice;
    }
    public Magacin getMagacin() {
        return this.magacin;
    }
    
    public void setMagacin(Magacin magacin) {
        this.magacin = magacin;
    }

    public int getNapredovanje() {
        return napredovanje;
    }

    public void setNapredovanje(int napredovanje) {
        this.napredovanje = napredovanje;
    }
  
    public int getKolona() {
        return kolona;
    }

    public void setKolona(int kolona) {
        this.kolona = kolona;
    }

    public int getRed() {
        return red;
    }

    public void setRed(int red) {
        this.red = red;
    }

    public static void dodajSadnicu(Sadnicezasadjene sadnica) {
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        session.save(sadnica);
        session.getTransaction().commit();
        session.close();
    }
    
    public static Sadnicezasadjene dohvatiSadnicu(int idSadnice, Rasadnik rasadnik) {
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        Sadnicezasadjene sadnica = (Sadnicezasadjene) session.createCriteria(Sadnicezasadjene.class).add(Restrictions.eq("idSadnice", idSadnice)).add(Restrictions.eq("rasadnik.idRasadnika", rasadnik.getIdRasadnika())).uniqueResult();
        session.getTransaction().commit();
        session.close();
        return sadnica;
    }
    
}


