package beans;
// Generated Jun 2, 2020, 10:56:56 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import util.HibernateUtil;




/**
 * Detalji generated by hbm2java
 */
public class Detalji  implements java.io.Serializable {


     private int idDetalja;
     private Onlineprodavnica onlineprodavnica;
     private Poljoprivrednik poljoprivrednik;
     private int ocena;
     private String komentar;

    public Detalji() {
    }

    public Detalji(int idDetalja, Onlineprodavnica onlineprodavnica, Poljoprivrednik poljoprivrednik, int ocena, String komentar) {
       this.idDetalja = idDetalja;
       this.onlineprodavnica = onlineprodavnica;
       this.poljoprivrednik = poljoprivrednik;
       this.ocena = ocena;
       this.komentar = komentar;
    }
   
    public int getIdDetalja() {
        return this.idDetalja;
    }
    
    public void setIdDetalja(int idDetalja) {
        this.idDetalja = idDetalja;
    }
    public Onlineprodavnica getOnlineprodavnica() {
        return this.onlineprodavnica;
    }
    
    public void setOnlineprodavnica(Onlineprodavnica onlineprodavnica) {
        this.onlineprodavnica = onlineprodavnica;
    }
    public Poljoprivrednik getPoljoprivrednik() {
        return this.poljoprivrednik;
    }
    
    public void setPoljoprivrednik(Poljoprivrednik poljoprivrednik) {
        this.poljoprivrednik = poljoprivrednik;
    }
    public int getOcena() {
        return this.ocena;
    }
    
    public void setOcena(int ocena) {
        this.ocena = ocena;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }

public static List<Detalji> dohvatiKomentare(int idProdavnice) {
        List<Detalji> detalji = new ArrayList<Detalji>();
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        detalji = session.createCriteria(Detalji.class).add(Restrictions.eq("onlineprodavnica.idProdavnice", idProdavnice))
                .list();    //.add(Restrictions.eq("detalji.onlineprodavnica.naziv", nazivProizvoda)).list();
                //.add(Restrictions.eq("Onlineprodavnica.idProizvoda", idProizvoda)).list();
        session.getTransaction().commit();
        session.close();
        return detalji;    
}


public static List<Detalji> dohvatiKomentareSve() {
        List<Detalji> detalji = new ArrayList<Detalji>();
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        detalji = session.createCriteria(Detalji.class).list();   
        session.getTransaction().commit();
        session.close();
        return detalji;    
}


public static void sacuvajDetalj(Detalji detalj) {
        //Detalji.dohvatiKomentareSve().add(detalj);
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        session.save(detalj);
        session.getTransaction().commit();
        session.close();
    }

public static List<Detalji> dohvatiDetalje(String ime) {
    
    List<Detalji> detalji = new ArrayList<Detalji>();
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        Query q = session.createQuery("select * from detalji d, onlineprodavnica op where d.idProdavnice=op.idProdavnice and op.korisnickoImePred=?");
        q.setString(0, ime);
        detalji = q.list();
        session.getTransaction().commit();
        session.close();
        return detalji;
}

}


